### ISSUE TITLE
Worldmap stats may not be accurate

### ISSUE THREAD

**Issue by Danie10** [EliotBerriot/mnm#1]
I'm in South Africa and know there are one or two other South Africans I have seen on Mastodon, but the country shows no users. Neither does any country in Africa or South America.

**Comment by gled-rs** [comment]
I believe the information is based on the location of the instances; not the users.

**Comment by EliotBerriot** [comment]
@gled-rs you are absolutely right, this is something that I'll try to advertise better on the dashboard, because it's causing a lot of confusion among users.
