### ISSUE TITLE
Negative number of statuses

### ISSUE THREAD

**Issue by cerisara** [EliotBerriot/mnm#2]
It was reported about -149000 statuses per minute,
but this bug disappeared at the next refresh, so maybe it was nothing...

**Comment by EliotBerriot** [comment]
Thank you for reporting this, I'll try to see where this is coming from.

**Comment by EliotBerriot** [comment]
I cannot reproduce, I'll close this issue, feel free to reopen with screenshots and links to the dashboard / panel where it arises.
