### ISSUE TITLE
Duplication of some instances by capitalization

### ISSUE THREAD

**Issue by LeoTindall** [EliotBerriot/mnm#25]
This is likely a bug, as it results in issues with the results. See attached image where `mastodon.cloud` and `Mastodon.cloud` were counted separately
![double counting](https://user-images.githubusercontent.com/3290365/38506508-b058a2f4-3bdf-11e8-8a33-ef4f61ec6d5a.png)

**Comment by EliotBerriot** [comment]
Thank you for taking the time to report this. 

At the moment, those are the duplicates we have in the database:

```
1 duplicates found for instance pouet.social
1 duplicates found for instance equestria.social
1 duplicates found for instance mastodon.cloud
1 duplicates found for instance mastodon.blue
```

Solving this properly would involve:

1. Deleting those duplicates from the database
2. Adding a unique constraint somewhere to ensure it does not happen again

**Comment by EliotBerriot** [comment]
@LeoTindall I've pushed a commit to fix this, and removed the duplicate from the database, can you check on your side and confirm it is ok? :)

Also, ping @Gargron

**Comment by LeoTindall** [comment]
Looks good. Thanks!
