### ISSUE TITLE
Duplication of some instances by subdomain

### ISSUE THREAD

**Issue by Gargron** [EliotBerriot/mnm#27]
In particular, test.switter.at appears as well as switter.at, they are clearly the same instance because they have the same number of users. I suggest maybe deduping based on subdomain.

With ALTERNATE_DOMAIN and WEB_DOMAIN, some instances indeed are reachable through different domains....

**Comment by EliotBerriot** [comment]
So assuming we have an instance y.z in database, and we're seing a new instance x.y.z, we would skip it entirely. That's doable. In the meantime, I'll exclude test.switter.at manually from the stats.
