### ISSUE TITLE
Use country in URL if there is one for more accurate location

### ISSUE THREAD

**Issue by Vanecx** [EliotBerriot/mnm#6]
In the worldmap, instances are located based on where their servers are, which is often inaccurate.

An option would be to take into account the top-level domain name, and if it's a country, use it. If it's not, then use the server as 2nd choice.

So : 
mastodon.pirateparty.be would be considered Belgian
mastodon.blue would be considered [insert server country]

(Problem : top-level domain names such as ".me" are often used in another way and not as a country...)

**Comment by EliotBerriot** [comment]
I'll be deploying a naive implementation for this thanks to https://github.com/mledoze/countries/blob/master/countries.json data:

1. If the tld is a country tld, we use it,
2. Otherwise, we fallback to the IP country lookup
