### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by f6fvy** [EliotBerriot/mnm#7]
The title of the world map is "Worldmap of **Maston** users" instead of "Worldmap of **Mastodon** users" (I guess).

**Comment by EliotBerriot** [comment]
Wow, I guess that was too big for me to see. I've corrected that, thanks!

**Comment by f6fvy** [comment]
Not fixed in the "Network drilldown" dashboard ;-)

**Comment by EliotBerriot** [comment]
This time, this shoudl be (hopefully) fixed  :p
